id:
name: GitOps.PullRequestIssueManagement
description: GitOps.PullRequestIssueManagement primitive
owner:
resource: repository
disabled: false
where:
configuration:
    resourceManagementConfiguration:
        scheduledSearches:
            - description:
              frequencies:
                  - hourly:
                        hour: 6
              filters:
                  - isIssue
                  - isOpen
                  - hasLabel:
                        label: "Needs: Author Feedback :pencil2:"
                  - hasLabel:
                        label: "Status: No Recent Activity"
                  - noActivitySince:
                        days: 3
              actions:
                  - closeIssue
            - description:
              frequencies:
                  - hourly:
                        hour: 6
              filters:
                  - isIssue
                  - isOpen
                  - hasLabel:
                        label: "Needs: Author Feedback :pencil2:"
                  - noActivitySince:
                        days: 4
                  - isNotLabeledWith:
                        label: "Status: No Recent Activity"
              actions:
                  - addLabel:
                        label: "Status: No Recent Activity"
                  - addReply:
                        reply: This issue has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **4 days**. It will be closed if no further activity occurs **within 3 days of this comment**.
            - description:
              frequencies:
                  - hourly:
                        hour: 6
              filters:
                  - isIssue
                  - isOpen
                  - hasLabel:
                        label: "Resolution: Duplicate"
                  - noActivitySince:
                        days: 1
              actions:
                  - addReply:
                        reply: This issue has been marked as duplicate and has not had any activity for **1 day**. It will be closed for housekeeping purposes.
                  - closeIssue
            - description:
              frequencies:
                  - hourly:
                        hour: 6
              filters:
                  - isPullRequest
                  - isOpen
                  - hasLabel:
                        label: "Needs: Author Feedback :pencil2:"
                  - hasLabel:
                        label: "Status: No Recent Activity"
                  - noActivitySince:
                        days: 7
              actions:
                  - closeIssue
            - description:
              frequencies:
                  - hourly:
                        hour: 6
              filters:
                  - isPullRequest
                  - isOpen
                  - hasLabel:
                        label: "Needs: Author Feedback :pencil2:"
                  - noActivitySince:
                        days: 7
                  - isNotLabeledWith:
                        label: "Status: No Recent Activity"
              actions:
                  - addLabel:
                        label: "Status: No Recent Activity"
                  - addReply:
                        reply: This pull request has been automatically marked as stale because it has been marked as requiring author feedback but has not had any activity for **7 days**. It will be closed if no further activity occurs **within 7 days of this comment**.
        eventResponderTasks:
            - if:
                  - payloadType: Issue_Comment
                  - isAction:
                        action: Created
                  - isActivitySender:
                        issueAuthor: True
                  - hasLabel:
                        label: "Needs: Author Feedback :pencil2:"
                  - isOpen
              then:
                  - addLabel:
                        label: "Needs: Attention :wave:"
                  - removeLabel:
                        label: "Needs: Author Feedback :pencil2:"
              description:
            - if:
                  - payloadType: Issues
                  - not:
                        isAction:
                            action: Closed
                  - hasLabel:
                        label: "Status: No Recent Activity"
              then:
                  - removeLabel:
                        label: "Status: No Recent Activity"
              description:
            - if:
                  - payloadType: Issue_Comment
                  - hasLabel:
                        label: "Status: No Recent Activity"
              then:
                  - removeLabel:
                        label: "Status: No Recent Activity"
              description:
            - if:
                  - payloadType: Pull_Request
              then:
                  - inPrLabel:
                        label: "PR: Referenced :eyes:"
              description:
            - if:
                  - payloadType: Pull_Request_Review
                  - isAction:
                        action: Submitted
                  - isReviewState:
                        reviewState: Changes_requested
              then:
                  - addLabel:
                        label: "Needs: Author Feedback :pencil2:"
              description:
            - if:
                  - payloadType: Pull_Request
                  - isActivitySender:
                        issueAuthor: True
                  - not:
                        isAction:
                            action: Closed
                  - hasLabel:
                        label: "Needs: Author Feedback :pencil2:"
              then:
                  - removeLabel:
                        label: "Needs: Author Feedback :pencil2:"
              description:
            - if:
                  - payloadType: Issue_Comment
                  - isActivitySender:
                        issueAuthor: True
                  - hasLabel:
                        label: "Needs: Author Feedback :pencil2:"
              then:
                  - removeLabel:
                        label: "Needs: Author Feedback :pencil2:"
              description:
            - if:
                  - payloadType: Pull_Request_Review
                  - isActivitySender:
                        issueAuthor: True
                  - hasLabel:
                        label: "Needs: Author Feedback :pencil2:"
              then:
                  - removeLabel:
                        label: "Needs: Author Feedback :pencil2:"
              description:
            - if:
                  - payloadType: Pull_Request
                  - not:
                        isAction:
                            action: Closed
                  - hasLabel:
                        label: "Status: No Recent Activity"
              then:
                  - removeLabel:
                        label: "Status: No Recent Activity"
              description:
            - if:
                  - payloadType: Issue_Comment
                  - hasLabel:
                        label: "Status: No Recent Activity"
              then:
                  - removeLabel:
                        label: "Status: No Recent Activity"
              description:
            - if:
                  - payloadType: Pull_Request_Review
                  - hasLabel:
                        label: "Status: No Recent Activity"
              then:
                  - removeLabel:
                        label: "Status: No Recent Activity"
              description:
            - if:
                  - payloadType: Pull_Request
                  - isOpen
                  - or:
                        - includesModifiedFiles:
                              files:
                                  - Makefile
                        - includesModifiedFiles:
                              files:
                                  - .github/workflows/
              then:
                  - addLabel:
                        label: "PR: Modified Workflows :warning:"
              description:
            - if:
                  - payloadType: Issues
                  - isAssignedToSomeone
              then:
                  - removeLabel:
                        label: "Needs: Triage :mag:"
              description:
            - if:
                  - payloadType: Pull_Request
                  - isAssignedToSomeone
              then:
                  - removeLabel:
                        label: "Needs: Triage :mag:"
              description:
            - if:
                  - payloadType: Issues
                  - labelAdded:
                        label: "Needs: Author Feedback :pencil2:"
              then:
                  - removeLabel:
                        label: "Needs: Attention :wave:"
              description:
onFailure:
onSuccess:
