---
name: Docs test

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  workflow_dispatch:

jobs:
  docstest:
    name: Docs test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'

      - name: Install tools
        run: make tools

      - name: Check *.md files
        run: |
          echo "==> Running make docs"
          make docs
          echo "==> Testing for changes to .md files"
          CHANGES=$(git status -suno)
          if [ "$CHANGES" ]; then
            echo "Documentation is not up to date or formatted correctly."
            echo "Run 'make docs' locally and commit the changes to fix."
            exit 1
          fi
