---
name: Test

on:
  pull_request_target:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    environment: CSUTF
    name: Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup go
        uses: actions/setup-go@v2
        with:
          go-version: '1.18.x'

      - name: Go test
        run: go test
        working-directory: ${{ github.workspace }}/tests
