---
name: Unit test

on:
  pull_request:
    types: ['opened', 'synchronize']
  workflow_dispatch:

jobs:
  unittest:
    name: Unit test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        terraform_version: ['~1.0.0', '~1.1.0', '~1.2.0']
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ matrix.terraform_version }}
          terraform_wrapper: false

      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'

      - name: Go test
        run: make test
