---
name: Housekeeping - Cancel subscriptions
on:
  schedule:
    - cron: "21 3 * * *" # daily at 3:21
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  cancelsubscriptions:
    name: Housekeeping - Cancel subscriptions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          allow-no-subscriptions: true

      - name: Azure cancel subscriptions
        uses: azure/CLI@v1
        continue-on-error: true
        with:
          inlineScript: |
            az account subscription list \
              | jq -r '.[] | select(.state == "Enabled") | select(.displayName | test("^testdeploy.*")) | .subscriptionId' \
              | xargs -L1 az account subscription cancel --yes --id

      - name: Azure logout
        uses: azure/CLI@v1
        if: always()
        with:
          inlineScript: |
            az logout
            az cache purge
            az account clear
