---
name: Linting
on:
  pull_request:
    types: ['opened', 'synchronize']

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run github/super-linter/slim
        uses: github/super-linter/slim@v4
        env:
          # Lint all code
          VALIDATE_ALL_CODEBASE: true
          FILTER_REGEX_EXCLUDE: '.*tests/vendor/.*'
          # Need to define main branch as default
          # is set to master in super-linter
          DEFAULT_BRANCH: main
          # Enable setting the status of each individual linter
          # run in the Checks section of a pull request
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # The following linter types will be enabled:
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_GITHUB_ACTIONS: true
          VALIDATE_JSON: true
          VALIDATE_MARKDOWN: true
          VALIDATE_TERRAFORM_TERRASCAN: true
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_YAML: true
          # VALIDATE_GO: true # Disabled because it down not work :(
          # Additional settings:
          # If a shell script is not executable, the bash-exec
          # linter will report an error when set to true
          ERROR_ON_MISSING_EXEC_BIT: true
      - name: Setup go
        uses: actions/setup-go@v3
        with:
          go-version: '1.18.x'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.46.2
          working-directory: ${{ github.workspace }}/tests
