---
name: Test azurerm auth

on:
  pull_request:
    types: ['opened', 'reopened', 'synchronize']
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  testauth:
    name: Test auth
    runs-on: ubuntu-latest
    environment: CSUTF-RO
    if: github.event.pull_request.head.repo.full_name == 'Azure/terraform-azurerm-alz-landing-zone'
    steps:
      - name: env
        run: env | sort

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: '~1.2.0'

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform init
        run: |
          terraform init
        working-directory: ${{ github.workspace }}/testazurerm
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}

      - name: Terraform plan
        run: |
          terraform plan
        working-directory: ${{ github.workspace }}/testazurerm
        env:
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
